FROM node:stretch
#FROM node:alpine


RUN apt-get update && apt-get install -y \
  supervisor \
  apache2 \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

ENV TZ=America/Argentina/Buenos_Aires
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone


COPY docker/supervisor/apache.conf /etc/supervisor/conf.d
COPY docker/apache/000-default.conf /etc/apache2/sites-available
COPY docker/entrypoint.sh /
COPY src /src

RUN a2enmod rewrite

ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/src/node_modules/.bin/

WORKDIR /src

#para evitar problemas con la instalacion del angular
USER node
RUN mkdir -p /home/node/.npm-global
ENV PATH=/home/node/.npm-global/bin:$PATH
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
RUN npm install -g --save @angular/cli

#RUN mkdir -p /usr/local/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp && chmod -R a+wrX /usr/local/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp
#RUN cd /src && npm install @angular/cli
#RUN cd /src && npm i -g npm
#RUN cd /src && npm install --global --save --ensure --unsafe @angular/cli
RUN cd /src/assistance && npm install
RUN cd /src/assistance && ng build --prod --build-optimizer

EXPOSE 80

ENTRYPOINT ["/entrypoint.sh"]
#ENTRYPOINT ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf",  "--nodaemon"]
